-- PG Workbench practice dataset v1.0. Synthetic, deterministic data.
-- PostgreSQL 16+ or PGlite. Run in an EMPTY database named pg_workbench.
-- This creates academy (sample data) and lab (your design exercises).
-- It intentionally does not drop or overwrite an existing schema.
BEGIN;
CREATE SCHEMA academy;
CREATE SCHEMA lab;
SET search_path TO academy, public;
CREATE TABLE countries (country_code char(2) PRIMARY KEY, country_name text NOT NULL, region text NOT NULL);
CREATE TABLE categories (category_id integer PRIMARY KEY, name text NOT NULL UNIQUE, parent_id integer REFERENCES categories);
CREATE TABLE suppliers (supplier_id integer PRIMARY KEY, name text NOT NULL, country_code char(2) REFERENCES countries, lead_days integer CHECK (lead_days > 0));
CREATE TABLE customers (customer_id integer PRIMARY KEY, full_name text NOT NULL, email text NOT NULL UNIQUE, country_code char(2) REFERENCES countries, signup_date date NOT NULL, segment text NOT NULL CHECK(segment IN ('consumer','business','enterprise')), referred_by integer REFERENCES customers, preferences jsonb NOT NULL DEFAULT '{}');
CREATE TABLE addresses (address_id integer PRIMARY KEY, customer_id integer NOT NULL REFERENCES customers, city text NOT NULL, address_type text CHECK(address_type IN ('billing','shipping')), postcode text);
CREATE TABLE products (product_id integer PRIMARY KEY, name text NOT NULL, category_id integer NOT NULL REFERENCES categories, supplier_id integer REFERENCES suppliers, price numeric(10,2) NOT NULL CHECK(price>0), cost numeric(10,2) NOT NULL CHECK(cost>=0), active boolean NOT NULL DEFAULT true, attributes jsonb NOT NULL DEFAULT '{}');
CREATE TABLE orders (order_id integer PRIMARY KEY, customer_id integer NOT NULL REFERENCES customers, order_date date NOT NULL, status text NOT NULL CHECK(status IN ('delivered','shipped','pending','cancelled')), channel text NOT NULL CHECK(channel IN ('web','mobile','partner')), shipping_fee numeric(10,2) NOT NULL DEFAULT 0 CHECK(shipping_fee>=0));
CREATE TABLE order_items (order_item_id integer PRIMARY KEY, order_id integer NOT NULL REFERENCES orders, product_id integer NOT NULL REFERENCES products, quantity integer NOT NULL CHECK(quantity>0), unit_price numeric(10,2) NOT NULL, discount_pct numeric(5,2) NOT NULL CHECK(discount_pct BETWEEN 0 AND 100), UNIQUE(order_id,product_id));
CREATE TABLE payments (payment_id integer PRIMARY KEY, order_id integer NOT NULL UNIQUE REFERENCES orders, paid_at date NOT NULL, amount numeric(12,2) NOT NULL CHECK(amount>=0), method text NOT NULL, status text NOT NULL CHECK(status IN ('captured','refunded')));
CREATE TABLE shipments (shipment_id integer PRIMARY KEY, order_id integer NOT NULL UNIQUE REFERENCES orders, shipped_at date NOT NULL, delivered_at date, carrier text NOT NULL, CHECK(delivered_at IS NULL OR delivered_at>=shipped_at));
CREATE TABLE returns (return_id integer PRIMARY KEY, order_item_id integer NOT NULL UNIQUE REFERENCES order_items, returned_at date NOT NULL, reason text NOT NULL, refund_amount numeric(10,2) NOT NULL CHECK(refund_amount>=0));
CREATE TABLE warehouses (warehouse_id integer PRIMARY KEY, name text NOT NULL, country_code char(2) REFERENCES countries);
CREATE TABLE inventory (warehouse_id integer REFERENCES warehouses, product_id integer REFERENCES products, quantity integer NOT NULL CHECK(quantity>=0), reorder_level integer NOT NULL CHECK(reorder_level>=0), PRIMARY KEY(warehouse_id,product_id));
CREATE TABLE departments (department_id integer PRIMARY KEY, name text NOT NULL UNIQUE, budget numeric(12,2) NOT NULL);
CREATE TABLE employees (employee_id integer PRIMARY KEY, full_name text NOT NULL, department_id integer NOT NULL REFERENCES departments, manager_id integer REFERENCES employees, salary numeric(12,2) NOT NULL CHECK(salary>0), hired_on date NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE projects (project_id integer PRIMARY KEY, name text NOT NULL, department_id integer REFERENCES departments, start_date date NOT NULL, budget numeric(12,2) NOT NULL);
CREATE TABLE employee_projects (employee_id integer REFERENCES employees, project_id integer REFERENCES projects, allocation_pct integer CHECK(allocation_pct BETWEEN 1 AND 100), PRIMARY KEY(employee_id,project_id));
CREATE TABLE timesheets (timesheet_id integer PRIMARY KEY, employee_id integer REFERENCES employees, project_id integer REFERENCES projects, work_date date NOT NULL, hours numeric(4,1) CHECK(hours BETWEEN 0 AND 24));
CREATE TABLE regions (region_id integer PRIMARY KEY, name text NOT NULL UNIQUE);
CREATE TABLE sites (site_id integer PRIMARY KEY, site_name text NOT NULL UNIQUE, region_id integer NOT NULL REFERENCES regions, city text NOT NULL, latitude numeric(8,5), longitude numeric(8,5));
CREATE TABLE cells (cell_id integer PRIMARY KEY, site_id integer NOT NULL REFERENCES sites, cell_name text NOT NULL UNIQUE, technology text NOT NULL CHECK(technology IN ('LTE','5G')), band integer NOT NULL, azimuth integer CHECK(azimuth>=0 AND azimuth<360));
CREATE TABLE cell_metrics (cell_id integer REFERENCES cells, metric_date date, dl_traffic_gb numeric(10,2) NOT NULL, dl_throughput_mbps numeric(8,2) NOT NULL, prb_util_pct numeric(5,2) CHECK(prb_util_pct BETWEEN 0 AND 100), availability_pct numeric(5,2) CHECK(availability_pct BETWEEN 0 AND 100), PRIMARY KEY(cell_id,metric_date));
CREATE TABLE incidents (incident_id integer PRIMARY KEY, cell_id integer REFERENCES cells, opened_at timestamp NOT NULL, closed_at timestamp, severity text NOT NULL CHECK(severity IN ('critical','major','minor')), category text NOT NULL, CHECK(closed_at IS NULL OR closed_at>=opened_at));
CREATE TABLE subscriptions (subscription_id integer PRIMARY KEY, customer_id integer NOT NULL REFERENCES customers, plan text NOT NULL, started_on date NOT NULL, ended_on date, monthly_fee numeric(10,2) NOT NULL CHECK(monthly_fee>=0), CHECK(ended_on IS NULL OR ended_on>=started_on));
CREATE TABLE events (event_id integer PRIMARY KEY, customer_id integer REFERENCES customers, event_at timestamp NOT NULL, event_type text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}');
INSERT INTO countries VALUES ('PK','Pakistan','Asia'),('GB','United Kingdom','Europe'),('US','United States','Americas'),('DE','Germany','Europe'),('AE','United Arab Emirates','Asia'),('CA','Canada','Americas'),('FR','France','Europe'),('AU','Australia','Oceania');
INSERT INTO categories VALUES (1,'Computing',NULL),(2,'Networking',NULL),(3,'Accessories',1),(4,'Displays',1),(5,'Storage',1),(6,'Audio',NULL),(7,'Mobile',NULL),(8,'Office',NULL);
INSERT INTO suppliers SELECT g,'Supplier '||lpad(g::text,2,'0'),(ARRAY['PK','GB','US','DE','AE','CA','FR','AU'])[1+g%8],3+g%18 FROM generate_series(1,20) g;
INSERT INTO customers SELECT g,(ARRAY['Aisha','Daniel','Noor','Omar','Maya','Alex','Sara','Bilal','Zoe','Hassan'])[1+g%10]||' '||(ARRAY['Khan','Ali','Smith','Wilson','Chen','Ahmed','Brown'])[1+(g/10)%7]||' '||g,'learner'||g||'@example.test',(ARRAY['PK','GB','US','DE','AE','CA','FR','AU'])[1+g%8],DATE '2023-01-01'+(g*7%600),(ARRAY['consumer','business','enterprise'])[1+g%3],CASE WHEN g>10 AND g%4=0 THEN 1+g%10 END,jsonb_build_object('newsletter',g%3=0,'language',CASE WHEN g%5=0 THEN 'ur' ELSE 'en' END) FROM generate_series(1,1200) g;
INSERT INTO addresses SELECT g,1+(g-1)%1200,(ARRAY['Lahore','London','Seattle','Berlin','Dubai','Toronto','Paris','Sydney'])[1+g%8],CASE WHEN g%2=0 THEN 'billing' ELSE 'shipping' END,CASE WHEN g%11=0 THEN NULL ELSE 'P'||lpad(g::text,5,'0') END FROM generate_series(1,1500) g;
INSERT INTO products SELECT g,(ARRAY['Laptop','Router','Cable','Monitor','SSD','Headset','Phone','Desk'])[1+(g-1)%8]||' '||lpad(g::text,3,'0'),1+(g-1)%8,1+(g-1)%20,round((20+g*17%980)::numeric+0.99,2),round((10+g*11%400)::numeric,2),g%17<>0,jsonb_build_object('color',(ARRAY['black','silver','blue'])[1+g%3],'warranty_months',12*(1+g%3)) FROM generate_series(1,240) g;
INSERT INTO orders SELECT g,1+((g*17+g/11)%1100),DATE '2025-01-01'+((g*13+g/31)%365),CASE WHEN g%13=0 THEN 'cancelled' WHEN g%11=0 THEN 'pending' WHEN g%7=0 THEN 'shipped' ELSE 'delivered' END,(ARRAY['web','mobile','partner'])[1+g%3],CASE WHEN g%5=0 THEN 0 ELSE 4.99 END FROM generate_series(1,10000) g;
INSERT INTO order_items SELECT (o.order_id-1)*3+k,o.order_id,p.product_id,1+(o.order_id+k)%4,p.price,(o.order_id+k)%4*5 FROM orders o CROSS JOIN generate_series(1,3) k JOIN products p ON p.product_id=1+(o.order_id*7+k*11)%220;
INSERT INTO payments SELECT o.order_id,o.order_id,o.order_date+1,round(sum(i.quantity*i.unit_price*(1-i.discount_pct/100))+o.shipping_fee,2),(ARRAY['card','bank','wallet'])[1+o.order_id%3],'captured' FROM orders o JOIN order_items i USING(order_id) WHERE o.status IN ('delivered','shipped') GROUP BY o.order_id;
INSERT INTO shipments SELECT order_id,order_id,order_date+1,CASE WHEN status='delivered' THEN order_date+2+order_id%8 END,(ARRAY['DHL','FedEx','LocalPost'])[1+order_id%3] FROM orders WHERE status IN ('delivered','shipped');
INSERT INTO returns SELECT i.order_item_id,i.order_item_id,o.order_date+15,(ARRAY['damaged','wrong_item','changed_mind'])[1+i.order_item_id%3],round(i.unit_price*(1-i.discount_pct/100),2) FROM order_items i JOIN orders o USING(order_id) WHERE o.status='delivered' AND i.order_item_id%37=0;
INSERT INTO warehouses VALUES (1,'Central','PK'),(2,'West','GB'),(3,'East','US');
INSERT INTO inventory SELECT w.warehouse_id,p.product_id,(p.product_id*w.warehouse_id*7)%150,20+p.product_id%10 FROM warehouses w CROSS JOIN products p;
INSERT INTO departments VALUES (1,'Engineering',1400000),(2,'Analytics',600000),(3,'Operations',900000),(4,'Sales',750000),(5,'Support',450000),(6,'Finance',500000);
INSERT INTO employees SELECT g,'Employee '||lpad(g::text,3,'0'),1+(g-1)%6,CASE WHEN g>6 THEN 1+(g-1)%6 END,(40000+((g*1700)%80000))::numeric,DATE '2020-01-01'+g*11,g%19<>0 FROM generate_series(1,180) g;
INSERT INTO projects SELECT g,'Project '||g,1+(g-1)%6,DATE '2025-01-01'+g*7,20000+g*4000 FROM generate_series(1,18) g;
INSERT INTO employee_projects SELECT e.employee_id,1+(e.employee_id+k*6)%18,50 FROM employees e CROSS JOIN generate_series(0,1) k;
INSERT INTO timesheets SELECT g,1+(g-1)%180,1+((1+(g-1)%180)+((g/180)%2)*6)%18,DATE '2025-10-01'+(g/180)%30,4+(g%5)*0.5 FROM generate_series(1,3000) g;
INSERT INTO regions VALUES (1,'North'),(2,'South'),(3,'Central'),(4,'East'),(5,'West');
INSERT INTO sites SELECT g,'SITE_'||lpad(g::text,3,'0'),1+(g-1)%5,(ARRAY['Islamabad','Karachi','Lahore','Faisalabad','Peshawar'])[1+(g-1)%5],24+g*0.07,67+g*0.04 FROM generate_series(1,100) g;
INSERT INTO cells SELECT g,1+(g-1)/6,'CELL_'||lpad(g::text,4,'0'),CASE WHEN g%4=0 THEN '5G' ELSE 'LTE' END,(ARRAY[3,8,1,78])[1+g%4],((g-1)%3)*120 FROM generate_series(1,600) g;
INSERT INTO cell_metrics SELECT c.cell_id,DATE '2025-11-01'+d,round((5+((c.cell_id*13+d*7)%950)/10.0)::numeric,2),round((0.5+((c.cell_id*7+d*11)%480)/10.0)::numeric,2),round((20+((c.cell_id*19+d*17)%800)/10.0)::numeric,2),CASE WHEN (c.cell_id+d)%23=0 THEN 94.5 ELSE 99.9 END FROM cells c CROSS JOIN generate_series(0,29) d;
INSERT INTO incidents SELECT g,1+g*13%600,TIMESTAMP '2025-11-01 08:00:00'+(g%29)*INTERVAL '1 day',CASE WHEN g%7<>0 THEN TIMESTAMP '2025-11-01 08:00:00'+(g%29)*INTERVAL '1 day'+(1+g%48)*INTERVAL '1 hour' END,(ARRAY['critical','major','minor'])[1+g%3],(ARRAY['power','transport','hardware','capacity'])[1+g%4] FROM generate_series(1,300) g;
INSERT INTO subscriptions SELECT g,g,(ARRAY['basic','pro','team'])[1+g%3],DATE '2024-01-01'+g%360,CASE WHEN g%5=0 THEN DATE '2025-07-01'+g%120 END,(ARRAY[9.99,29.99,79.99])[1+g%3] FROM generate_series(1,900) g;
INSERT INTO events SELECT g,CASE WHEN g%17=0 THEN NULL ELSE 1+g%1200 END,TIMESTAMP '2025-11-01'+(g%30)*INTERVAL '1 day'+(g%24)*INTERVAL '1 hour',(ARRAY['page_view','add_to_cart','checkout','purchase'])[1+g%4],jsonb_build_object('device',CASE WHEN g%3=0 THEN 'mobile' ELSE 'desktop' END,'campaign',(ARRAY['organic','autumn','referral'])[1+g%3],'duration_seconds',1+g%200) FROM generate_series(1,6000) g;
CREATE INDEX idx_orders_customer_date ON orders(customer_id,order_date);
CREATE INDEX idx_items_product ON order_items(product_id);
CREATE INDEX idx_customers_country ON customers(country_code);
CREATE INDEX idx_metrics_date ON cell_metrics(metric_date);
CREATE INDEX idx_incidents_open ON incidents(cell_id) WHERE closed_at IS NULL;
CREATE VIEW order_totals AS SELECT o.order_id,o.customer_id,o.order_date,o.status,round(sum(i.quantity*i.unit_price*(1-i.discount_pct/100)),2) AS merchandise_total,o.shipping_fee FROM orders o JOIN order_items i USING(order_id) GROUP BY o.order_id;
COMMENT ON SCHEMA academy IS 'PG Workbench deterministic synthetic data. Commerce dates: 2025. Telecom: November 2025. Currency: USD for learning.';
COMMENT ON SCHEMA lab IS 'User-created tables for design and DML exercises.';
COMMIT;
ANALYZE;
