import React,{useState,useEffect} from 'react';
import {Users,UserPlus,Search,RefreshCw,ArrowLeft,ArrowRight,CheckCircle2} from 'lucide-react';
import {supabase} from './client.js';
import {curriculum,exercises,interviewCards} from '../data/curriculum.js';
const when=value=>value?new Date(value).toLocaleString():'Not yet';
const passed=state=>exercises.filter(e=>state?.completed?.[e.id]).length;
export default function Admin({client=supabase}){
 const [search,setSearch]=useState(''),[offset,setOffset]=useState(0),[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState(null);
 const [username,setUsername]=useState(''),[email,setEmail]=useState(''),[name,setName]=useState(''),[inviting,setInviting]=useState(false),[inviteMessage,setInviteMessage]=useState(''),[inviteError,setInviteError]=useState('');
 useEffect(()=>{let alive=true;setBusy(true);setError('');const timer=setTimeout(async()=>{try{
  const {data,error}=await client.rpc('admin_learners',{p_search:search.trim(),p_offset:offset});if(error)throw error;
  if(alive){setRows(data||[]);setSelected(prev=>prev?(data||[]).find(r=>r.id===prev.id)||null:null);}
 }catch(e){if(alive)setError(e.message);}finally{if(alive)setBusy(false);}},250);return()=>{alive=false;clearTimeout(timer);};},[search,offset,refresh]);
 async function invite(e){e.preventDefault();setInviting(true);setInviteError('');setInviteMessage('');try{
  const {data,error}=await client.auth.getSession();if(error)throw error;
  if(!data.session)throw new Error('Sign in again before inviting a learner.');
  const response=await fetch('/api/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({email,username,display_name:name})});
  const payload=await response.json();if(!response.ok)throw new Error(payload.message||'Invitation failed.');
  setInviteMessage(payload.message);setEmail('');setUsername('');setName('');setRefresh(n=>n+1);
 }catch(e){setInviteError(e.message);}finally{setInviting(false);}}
 const total=Number(rows[0]?.total||0);
 return <><div className="page-heading"><div><div className="eyebrow">INSTRUCTOR WORKSPACE</div><h1>Learner progress</h1><p>Find a username, follow the learning journey, and invite someone new.</p></div><button className="btn" onClick={()=>setRefresh(n=>n+1)} disabled={busy}><RefreshCw size={16}/> Refresh</button></div>
 <div className="admin-layout"><section className="card learner-list"><div className="card-heading"><h2><Users size={20}/> Your learners</h2><span className="tag">{busy?'Loading…':`${total} account${total===1?'':'s'}`}</span></div><label className="admin-search"><Search size={18}/><input aria-label="Search learners by username or name" placeholder="Search username or name…" maxLength={80} value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);setSelected(null);}}/></label>
 {error&&<p className="account-error" role="alert">{error}</p>}
 <div className="table-scroll"><table><thead><tr><th>Username</th><th>Plan</th><th>Completion</th><th>Last active</th><th/></tr></thead><tbody>{!busy&&rows.map(r=><tr key={r.id}><td><strong>{r.username}</strong><small className="learner-name">{r.display_name||'Learner'}{r.role==='admin'?' · Admin':''}</small></td><td>{r.learning?.plan?`${r.learning.plan} days`:'Not started'}</td><td><strong>{passed(r.learning)}/90</strong><small className="learner-name">{Math.round(passed(r.learning)/90*100)}%</small></td><td>{when(r.last_seen_at)}</td><td><button className="text-link" onClick={()=>setSelected(r)}>View</button></td></tr>)}</tbody></table></div>
 {busy?<div className="empty" role="status">Loading learners…</div>:!rows.length&&!error?<div className="empty">No learners match this search.</div>:null}
 <div className="admin-pagination"><button className="btn" disabled={offset===0||busy} onClick={()=>setOffset(n=>Math.max(0,n-50))}><ArrowLeft size={15}/> Previous</button><span>{rows.length?`${offset+1}–${offset+rows.length}`:'0'} of {total}</span><button className="btn" disabled={offset+rows.length>=total||busy} onClick={()=>setOffset(n=>n+50)}>Next <ArrowRight size={15}/></button></div></section>
 <aside className="card admin-invite"><div className="auth-card-icon"><UserPlus/></div><h2>Create a learner account</h2><p>Send an invitation so the learner can choose their own password.</p><form className="account-form" onSubmit={invite}><label>Full name<input value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><label>Username<input pattern="[a-z0-9_]{3,30}" minLength={3} maxLength={30} value={username} required onChange={e=>setUsername(e.target.value.toLowerCase())}/><small>Lowercase letters, digits and underscores.</small></label><label>Email address<input type="email" maxLength={254} value={email} required onChange={e=>setEmail(e.target.value)}/></label>{inviteError&&<p className="account-error" role="alert">{inviteError}</p>}{inviteMessage&&<p className="account-success" role="status">{inviteMessage}</p>}<button className="btn primary" disabled={inviting}>{inviting?'Sending invitation…':'Create & send invitation'}<ArrowRight size={16}/></button></form><small className="admin-note">New learners can also use Sign up on the welcome page. They receive learner access only.</small></aside></div>
 {selected&&<section className="card learner-detail"><div className="card-heading"><div><div className="eyebrow">LEARNING RECORD</div><h2>{selected.username}</h2><p>{selected.display_name} · Joined {when(selected.created_at)}</p></div><button className="btn" onClick={()=>setSelected(null)}>Close details</button></div><div className="learner-metrics"><div><strong>{passed(selected.learning)}/90</strong><span>Exercises completed</span></div><div><strong>{interviewCards.filter(c=>selected.learning?.reviewed?.[c.id]).length}/60</strong><span>Cards reviewed</span></div><div><strong>{selected.learning?.quizScore?`${selected.learning.quizScore.score}/20`:'—'}</strong><span>Latest quiz score</span></div><div><strong>{selected.learning?.day||'—'}</strong><span>Current plan day</span></div></div><div className="table-scroll"><table><thead><tr><th>Module</th><th>Completed exercises</th><th>With hints / solution</th></tr></thead><tbody>{curriculum.map(l=><tr key={l.id}><td>{l.id}. {l.title}</td><td>{l.exercises.filter(e=>selected.learning?.completed?.[e.id]).map(e=><span className="tag" key={e.id}><CheckCircle2 size={12}/> {e.id}</span>)}{!l.exercises.some(e=>selected.learning?.completed?.[e.id])&&'Not yet'}</td><td>{l.exercises.filter(e=>selected.learning?.completed?.[e.id]?.assisted).length}</td></tr>)}</tbody></table></div><p className="admin-note">Last progress save: {when(selected.updated_at)}. Last activity is updated while the learner has this app open.</p></section>}
 <div className="callout info"><p>These are learning records, not independently verified assessment results. Exercises run in each learner’s browser; imported progress is also counted. Private notes and SQL drafts are not shown here.</p></div></>;
}
